apiVersion: v1
kind: Secret
metadata:
  name: es-rds-arch-secret-go-worker-event
  namespace: test-a
type: Opaque
stringData:
  sasl: "scram_sha512"
  tls: "enable"
  username: "postgres"
  password: "mypass123$"